version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: test-tracking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test_tracking
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - test-tracking-network

  app:
    build: .
    container_name: test-tracking-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test_tracking?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - mysql
    networks:
      - test-tracking-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  test-tracking-network:
    driver: bridge 