server:
  port: 8080

spring:
  application:
    name: test-task-tracking
  
  datasource:
    url: jdbc:mysql://localhost:3306/test_tracking?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

jwt:
  secret: TestTrackingSecretKey2024ProductionEnvironmentWithEnhancedSecurityForHS512Algorithm
  expiration: 86400000 # 24小时

logging:
  level:
    com.testtracking: DEBUG
    org.springframework.security: DEBUG

# 钉钉通知配置
dingtalk:
  enabled: false  # 是否启用钉钉通知
  webhook:
    url: https://oapi.dingtalk.com/robot/send?access_token=your_access_token  # 钉钉机器人webhook地址
  secret: your_secret  # 钉钉机器人签名密钥（可选）

# 定时任务配置
  task:
    scheduling:
      pool:
        size: 5 